services:
  ursim:
    image: universalrobots/ursim_e-series
    container_name: ursim
    ports:
      - "5900:5900"
      - "6080:6080"
      - "29999:2999"
      - "30001-30004:30001-30004"
    environment:
      - ROBOT_MODEL=UR5
      - TZ=America/Bogota
    volumes:
      - "/c/Users/NOMBRE_USUARIO/.ursim/programs:/ursim/programs"
      - "/c/Users/NOMBRE_USUARIO/.ursim/urcaps:/urcaps"
